### ISSUE TITLE
[1.0.1] Error: ESLint couldn't find the plugin "eslint-plugin-disable"

### ISSUE THREAD

**Issue by joncursi** [mradionov/eslint-plugin-disable#14]
I am using `eslint-plugin-disable` inside my `eslint-config-myapp` package that I use throughout my projects. When I run `eslint` on these projects, I get the following error:

```
✖ eslint --quiet found some errors. Please fix them and try committing again.
          
          
Oops! Something went wrong! :(

ESLint: 4.14.0.
ESLint couldn't find the plugin "eslint-plugin-disable". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-disable is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

npm i eslint-plugin-disable@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

My ESLint install is local to each project, so I took the above advice and tried installing this package as a devDependency in each of my projects that use my shared config.

Same error, though!

**Comment by mradionov** [comment]
It might be related to the recent 1.0.1 update I've published, I'll take a look, thanks!

**Comment by mradionov** [comment]
Have you used eslint-plugin-disable in your custom config before and it has just broke? Or is it after you've first tried to add it to the config it failed?

**Comment by joncursi** [comment]
Correct. It just broke with the new release

**Comment by mradionov** [comment]
Could you please share with me eslint configs for you custom config `eslint-config-myapp` and for any actual project that uses this config? I assume that all NPM modules installations are local to each project.

**Comment by joncursi** [comment]
Here's the relevant guts of my eslint config package:

```json
{
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "plugins": [
    "disable"
  ],
  "settings": {
    "eslint-plugin-disable": {
      "paths": {
        "filenames": [
          "**/*.tests.js",
          "**/tests.js"
        ],
        "flowtype": [
          "**/*.tests.js",
          "**/tests.js",
          "scripts/*.js"
        ]
      }
    }
  }
}
```

Here's an example of a project config:

```json
{
    "extends": [
      "@myapp/eslint-config"
    ]
  }
```

**Comment by mradionov** [comment]
Is eslint-plugin-disable present in a package.json for  `eslint-config-myapp` or the actual project? Can you see it in `node_modules/` for you project?

**Comment by joncursi** [comment]
@mradionov it's installed as a dependency of `@myapp/eslint-config` and not in the project itself.

I took a peak at `node_modules` of one of my downstream projects that was erroring and it actually wasn't there for some reason. Instead, it's under `node_modules/@myapp/eslint-config/node_modules/eslint-plugin-disable`.

However, on a separate downstream project that is not erroring, it was indeed present at `node_modules/eslint-plugin-disable`.

Any ideas on what the difference could be that would cause the module to be located in a different position in `node_modules`?

**Comment by joncursi** [comment]
Fixed by regenerating `package-lock.json`:

```
rm -rf node_modules package-lock.json
npm install
```
