### ISSUE TITLE
seems to not be working

### ISSUE THREAD

**Issue by tconroy** [mradionov/eslint-plugin-disable#15]
Given the following directory structure:
```
.eslintrc.json
src/
  components/
    header/
      index.jsx
      index.test.jsx
```

and the following `.eslintrc.json` config:
```json
{
  "extends": ["airbnb", "prettier", "prettier/react"],
  "plugins": ["react", "jsx-a11y", "import", "prettier", "disable"],
  "parserOptions": {
    "ecmaFeatures": {
      "modules": true,
      "jsx": true
    }
  },
  "settings": {
    "eslint-plugin-disable": {
      "paths": {
        "jsx-a11y": ["**/src/**/*.test.js", "**/src/**/*.test.jsx"]
      }
    }
  },
  "env": {
    "browser": true,
    "jest": true
  },
}
```

and the following test file (index.test.jsx):
```js
import { h } from 'preact';
import { Link } from 'preact-router/match';
import { shallow } from 'preact-render-spy';
import Header from './index';

describe('Header', () => {
  test('Header renders 3 nav items', () => {
    const context = shallow(<Header />);
    expect(context.find('h1').text()).toBe('Preact App');
    expect(context.find(<Link />).length).toBe(3);
  });
});
```

I would expect to NOT get warnings from the `jsx-a11y` plugin -- however I am:

```
  12:25  error  The href attribute is required on an anchor. Provide a valid, navigable address as the href value  jsx-a11y/anchor-is-valid

✖ 1 problem (1 error, 0 warnings)
```

Any ideas? I've tried both the approach in the eslintrc as well as the comment-style, inlined in the file itself. neither seems to prevent the plugin from running.

**Comment by mradionov** [comment]
I'll take a look, thanks

**Comment by mradionov** [comment]
By the way, could you please provide an actual command you use to run eslint? `.jsx` is not a usual file extension and ESLint does not acknowledge it by default. Make sure you run:

```
eslint --ext .js,.jsx ...
```

**Comment by mradionov** [comment]
Seems to be working for me with your ESLint config, directory structure and test file. It would be great if you could also share your package.json, maybe there is something in there. I could post a minimal working sample in a separate repository and we could work from there in case you have a big project and it would b difficult to localize the problem.

**Comment by mradionov** [comment]
Closing for now. Feel free to re-open if you have some more information for me.
