### ISSUE TITLE
eslint --fix won't work

### ISSUE THREAD

**Issue by rgant** [mradionov/eslint-plugin-disable#16]
I've discovered that when the disable plugin is used that `eslint --fix` no longer changes. Removing `"disable"` from `"plugins":` causes `--fix` to work again. Is this expected behavior? any way around it?

**Comment by mradionov** [comment]
No, it is not expected behavior. Thank you for bringing this up, I'll take a look.

**Comment by mradionov** [comment]
@rgant fix for "--fix" is available in a new [1.0.2](https://www.npmjs.com/package/eslint-plugin-disable) version available on npm

**Comment by rgant** [comment]
Thanks for the quick turn around on this!
