### ISSUE TITLE
Duplicated peer and prod dependency.

### ISSUE THREAD

**Issue by Lighttree** [mradionov/eslint-plugin-disable#32]
I think this bug is valid for the package:

https://github.com/yarnpkg/yarn/issues/6285

It seems like `eslint` shouldn't be presented in both `dependencies` and `peerDependencies`.
https://github.com/mradionov/eslint-plugin-disable/blob/master/package.json#L25

Because this leads to `error An unexpected error occurred: "could not find a copy of eslint to link` during dependencies installation.

At least in the mono repo with "hoisted" dependencies.

**Comment by mradionov** [comment]
I removed `eslint` from `dependencies` and moved it to `devDependencies`, even though it seems like it was an issue with yarn. The fix is available in version 2.0.3.
